from __future__ import annotations

from datetime import datetime

from sqlalchemy import (
    JSON, BigInteger, Boolean, Column, DateTime, Enum, Float, ForeignKey, Index,
    Integer, String
)
from sqlalchemy.orm import relationship

from ..db.base import Base, EventDirection, VehicleStatus


class Event(Base):
    """One vehicle passing the gate. The core fact table."""

    __tablename__ = "events"

    id = Column(BigInteger().with_variant(Integer, "sqlite"), primary_key=True, index=True)
    #: Generated by the worker so ingest is idempotent: a retried submission
    #: after a network timeout must not create a second event.
    event_uid = Column(String(36), unique=True, index=True, nullable=True)

    camera_id = Column(Integer, ForeignKey("cameras.id"), nullable=True, index=True)
    plate_number = Column(String(32), index=True, nullable=False)
    plate_raw = Column(String(48), default="")

    vehicle_id = Column(Integer, ForeignKey("vehicles.id"), nullable=True, index=True)
    resident_id = Column(Integer, ForeignKey("residents.id"), nullable=True)

    direction = Column(Enum(EventDirection), default=EventDirection.unknown, index=True)
    status = Column(Enum(VehicleStatus), default=VehicleStatus.unknown, index=True)

    vehicle_type = Column(String(32), default="car")
    vehicle_color = Column(String(32), nullable=True)
    plate_color = Column(String(32), nullable=True)

    #: Recognition confidence after multi-frame validation, NOT a single OCR
    #: score. Replaces the prototype's ocr_confidence.
    plate_confidence = Column(Float, default=0.0)
    detect_confidence = Column(Float, default=0.0)
    validation_support = Column(Float, default=0.0)
    read_count = Column(Integer, default=0)
    distinct_variants = Column(Integer, default=0)
    grammar_valid = Column(Boolean, default=False)
    corrections = Column(JSON, default=list)

    vehicle_image_path = Column(String(512), nullable=True)
    plate_image_path = Column(String(512), nullable=True)
    snapshot_path = Column(String(512), nullable=True)

    track_id = Column(Integer, nullable=True)
    finalize_reason = Column(String(32), default="")
    #: The validator was not confident. Surfaced in the UI for review rather
    #: than hidden, because a missed resident is a complaint at the gate.
    is_disputed = Column(Boolean, default=False, index=True)
    is_manual_override = Column(Boolean, default=False)
    reviewed_by = Column(Integer, ForeignKey("users.id"), nullable=True)
    reviewed_at = Column(DateTime, nullable=True)

    detected_at = Column(DateTime, default=datetime.utcnow, index=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    vehicle = relationship("Vehicle")
    camera = relationship("Camera")
    resident = relationship("Resident")
    reads = relationship("EventRead", back_populates="event", cascade="all, delete-orphan")
    alerts = relationship("Alert", back_populates="event")

    __table_args__ = (
        # The three access patterns the UI actually has: the live feed, a
        # plate's history, and a camera's day.
        Index("ix_events_detected_at_desc", detected_at.desc()),
        Index("ix_events_plate_detected", "plate_number", "detected_at"),
        Index("ix_events_camera_detected", "camera_id", "detected_at"),
        Index("ix_events_status_detected", "status", "detected_at"),
    )


class EventRead(Base):
    """One accepted per-frame recognition, kept as the evidence trail.

    Two jobs: it answers an operator asking "why did it say UP32A81234?", and
    it is the labelled dataset that scripts/harvest_dataset.py mines for
    fine-tuning. Pruned by the janitor well before the events themselves.
    """

    __tablename__ = "event_reads"

    id = Column(BigInteger().with_variant(Integer, "sqlite"), primary_key=True)
    event_id = Column(
        BigInteger().with_variant(Integer, "sqlite"),
        ForeignKey("events.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    frame_ts = Column(Float, default=0.0)
    raw_text = Column(String(48), default="")
    normalized_text = Column(String(32), default="")
    rec_confidence = Column(Float, default=0.0)
    plate_det_confidence = Column(Float, default=0.0)
    quality_score = Column(Float, default=0.0)
    weight = Column(Float, default=0.0)
    plate_crop_path = Column(String(512), nullable=True)

    event = relationship("Event", back_populates="reads")
