"""phase1 schema: residents, camera_zones, event_reads, alerts, roles

Revision ID: 9a67a0a34836
Revises: 
Create Date: 2026-08-30 14:15:07.935085
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '9a67a0a34836'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='alertseverity'), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('channels', sa.JSON(), nullable=True),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=True),
    sa.Column('camera_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_code'), 'alert_rules', ['code'], unique=False)
    op.create_index(op.f('ix_alert_rules_id'), 'alert_rules', ['id'], unique=False)
    op.create_table('residents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('flat_number', sa.String(length=32), nullable=True),
    sa.Column('block', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_residents_flat_number'), 'residents', ['flat_number'], unique=False)
    op.create_index(op.f('ix_residents_id'), 'residents', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('camera_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('roi', 'line', 'mask', name='zonekind'), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('geometry', sa.JSON(), nullable=False),
    sa.Column('direction_hint', sa.String(length=8), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camera_zones_camera_id'), 'camera_zones', ['camera_id'], unique=False)
    op.create_index(op.f('ix_camera_zones_id'), 'camera_zones', ['id'], unique=False)
    op.create_table('plate_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('alias_plate', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plate_aliases_alias_plate'), 'plate_aliases', ['alias_plate'], unique=True)
    op.create_index(op.f('ix_plate_aliases_id'), 'plate_aliases', ['id'], unique=False)
    op.create_index(op.f('ix_plate_aliases_vehicle_id'), 'plate_aliases', ['vehicle_id'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(length=96), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='alertseverity'), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('new', 'acknowledged', 'resolved', name='alertstatus'), nullable=True),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_event_id'), 'alerts', ['event_id'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_rule_id'), 'alerts', ['rule_id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_table('event_reads',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('event_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('frame_ts', sa.Float(), nullable=True),
    sa.Column('raw_text', sa.String(length=48), nullable=True),
    sa.Column('normalized_text', sa.String(length=32), nullable=True),
    sa.Column('rec_confidence', sa.Float(), nullable=True),
    sa.Column('plate_det_confidence', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('plate_crop_path', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_reads_event_id'), 'event_reads', ['event_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('alert_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', name='notificationstatus'), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_alert_id'), 'notifications', ['alert_id'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.add_column('activity_logs', sa.Column('entity_type', sa.String(length=64), nullable=True))
    op.add_column('activity_logs', sa.Column('entity_id', sa.String(length=64), nullable=True))
    op.add_column('activity_logs', sa.Column('ip_address', sa.String(length=64), nullable=True))
    op.add_column('cameras', sa.Column('code', sa.String(length=32), nullable=True))
    op.add_column('cameras', sa.Column('rtsp_url_sub', sa.String(length=512), nullable=True))
    op.add_column('cameras', sa.Column('snapshot_from_main', sa.Boolean(), nullable=True))
    op.add_column('cameras', sa.Column('processing_fps', sa.Float(), nullable=True))
    op.add_column('cameras', sa.Column('detect_interval', sa.Integer(), nullable=True))
    op.add_column('cameras', sa.Column('model_profile', sa.String(length=64), nullable=True))
    op.add_column('cameras', sa.Column('health', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_cameras_code'), 'cameras', ['code'], unique=True)
    op.add_column('events', sa.Column('event_uid', sa.String(length=36), nullable=True))
    op.add_column('events', sa.Column('plate_raw', sa.String(length=48), nullable=True))
    op.add_column('events', sa.Column('resident_id', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('plate_confidence', sa.Float(), nullable=True))
    op.add_column('events', sa.Column('detect_confidence', sa.Float(), nullable=True))
    op.add_column('events', sa.Column('validation_support', sa.Float(), nullable=True))
    op.add_column('events', sa.Column('read_count', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('distinct_variants', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('grammar_valid', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('corrections', sa.JSON(), nullable=True))
    op.add_column('events', sa.Column('vehicle_image_path', sa.String(length=512), nullable=True))
    op.add_column('events', sa.Column('plate_image_path', sa.String(length=512), nullable=True))
    op.add_column('events', sa.Column('snapshot_path', sa.String(length=512), nullable=True))
    op.add_column('events', sa.Column('track_id', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('finalize_reason', sa.String(length=32), nullable=True))
    op.add_column('events', sa.Column('is_disputed', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('is_manual_override', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('reviewed_by', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.add_column('events', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('events', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False,
               autoincrement=True)
    # events.direction changes type: a camera may be configured "both", but an
    # individual event is an entry, an exit, or an honest "unknown". Postgres
    # cannot cast between enum types implicitly and has no target value for
    # 'both', so do it explicitly with a USING clause.
    op.execute("CREATE TYPE eventdirection AS ENUM ('in_', 'out_', 'unknown')")
    op.execute(
        "ALTER TABLE events ALTER COLUMN direction TYPE eventdirection "
        "USING (CASE direction::text "
        "         WHEN 'in_' THEN 'in_' "
        "         WHEN 'out_' THEN 'out_' "
        "         ELSE 'unknown' END)::eventdirection"
    )
    op.create_index('ix_events_camera_detected', 'events', ['camera_id', 'detected_at'], unique=False)
    op.create_index(op.f('ix_events_camera_id'), 'events', ['camera_id'], unique=False)
    op.create_index('ix_events_detected_at_desc', 'events', [sa.text('detected_at DESC')], unique=False)
    op.create_index(op.f('ix_events_direction'), 'events', ['direction'], unique=False)
    op.create_index(op.f('ix_events_event_uid'), 'events', ['event_uid'], unique=True)
    op.create_index(op.f('ix_events_is_disputed'), 'events', ['is_disputed'], unique=False)
    op.create_index('ix_events_plate_detected', 'events', ['plate_number', 'detected_at'], unique=False)
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    op.create_index('ix_events_status_detected', 'events', ['status', 'detected_at'], unique=False)
    op.create_index(op.f('ix_events_vehicle_id'), 'events', ['vehicle_id'], unique=False)
    op.create_foreign_key(None, 'events', 'residents', ['resident_id'], ['id'])
    op.create_foreign_key(None, 'events', 'users', ['reviewed_by'], ['id'])
    # Backfill before dropping: these columns hold every event the prototype
    # ever recorded, and an unbackfilled drop would silently empty the history
    # the client is paying to keep.
    op.execute("UPDATE events SET plate_confidence = COALESCE(ocr_confidence, 0)")
    op.execute("UPDATE events SET detect_confidence = COALESCE(confidence, 0)")
    op.execute("UPDATE events SET vehicle_image_path = image_path WHERE image_path IS NOT NULL")
    # Prototype events came from a single frame, and had no evidence trail.
    op.execute("UPDATE events SET read_count = 1, distinct_variants = 1 WHERE read_count IS NULL")
    op.execute("UPDATE events SET event_uid = gen_random_uuid()::text WHERE event_uid IS NULL")

    op.drop_column('events', 'image_path')
    op.drop_column('events', 'ocr_confidence')
    op.drop_column('events', 'confidence')
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    op.add_column('vehicles', sa.Column('plate_raw', sa.String(length=48), nullable=True))
    op.add_column('vehicles', sa.Column('resident_id', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('make_model', sa.String(length=64), nullable=True))
    op.add_column('vehicles', sa.Column('color', sa.String(length=32), nullable=True))
    op.add_column('vehicles', sa.Column('valid_from', sa.DateTime(), nullable=True))
    op.add_column('vehicles', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_vehicles_resident_id'), 'vehicles', ['resident_id'], unique=False)
    op.create_index(op.f('ix_vehicles_status'), 'vehicles', ['status'], unique=False)
    op.create_foreign_key(None, 'vehicles', 'residents', ['resident_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_index(op.f('ix_vehicles_status'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_resident_id'), table_name='vehicles')
    op.drop_column('vehicles', 'is_active')
    op.drop_column('vehicles', 'valid_from')
    op.drop_column('vehicles', 'color')
    op.drop_column('vehicles', 'make_model')
    op.drop_column('vehicles', 'resident_id')
    op.drop_column('vehicles', 'plate_raw')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'role_id')
    op.add_column('events', sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('ocr_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('image_path', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_index(op.f('ix_events_vehicle_id'), table_name='events')
    op.drop_index('ix_events_status_detected', table_name='events')
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_index('ix_events_plate_detected', table_name='events')
    op.drop_index(op.f('ix_events_is_disputed'), table_name='events')
    op.drop_index(op.f('ix_events_event_uid'), table_name='events')
    op.drop_index(op.f('ix_events_direction'), table_name='events')
    op.drop_index('ix_events_detected_at_desc', table_name='events')
    op.drop_index(op.f('ix_events_camera_id'), table_name='events')
    op.drop_index('ix_events_camera_detected', table_name='events')
    op.alter_column('events', 'direction',
               existing_type=sa.Enum('in_', 'out_', 'unknown', name='eventdirection'),
               type_=postgresql.ENUM('in_', 'out_', 'both', name='cameradirection'),
               existing_nullable=True)
    op.alter_column('events', 'id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('events', 'created_at')
    op.drop_column('events', 'reviewed_at')
    op.drop_column('events', 'reviewed_by')
    op.drop_column('events', 'is_manual_override')
    op.drop_column('events', 'is_disputed')
    op.drop_column('events', 'finalize_reason')
    op.drop_column('events', 'track_id')
    op.drop_column('events', 'snapshot_path')
    op.drop_column('events', 'plate_image_path')
    op.drop_column('events', 'vehicle_image_path')
    op.drop_column('events', 'corrections')
    op.drop_column('events', 'grammar_valid')
    op.drop_column('events', 'distinct_variants')
    op.drop_column('events', 'read_count')
    op.drop_column('events', 'validation_support')
    op.drop_column('events', 'detect_confidence')
    op.drop_column('events', 'plate_confidence')
    op.drop_column('events', 'resident_id')
    op.drop_column('events', 'plate_raw')
    op.drop_column('events', 'event_uid')
    op.execute("DROP TYPE IF EXISTS eventdirection")
    op.drop_index(op.f('ix_cameras_code'), table_name='cameras')
    op.drop_column('cameras', 'health')
    op.drop_column('cameras', 'model_profile')
    op.drop_column('cameras', 'detect_interval')
    op.drop_column('cameras', 'processing_fps')
    op.drop_column('cameras', 'snapshot_from_main')
    op.drop_column('cameras', 'rtsp_url_sub')
    op.drop_column('cameras', 'code')
    op.drop_column('activity_logs', 'ip_address')
    op.drop_column('activity_logs', 'entity_id')
    op.drop_column('activity_logs', 'entity_type')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_alert_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_event_reads_event_id'), table_name='event_reads')
    op.drop_table('event_reads')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_rule_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_event_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('settings')
    op.drop_index(op.f('ix_plate_aliases_vehicle_id'), table_name='plate_aliases')
    op.drop_index(op.f('ix_plate_aliases_id'), table_name='plate_aliases')
    op.drop_index(op.f('ix_plate_aliases_alias_plate'), table_name='plate_aliases')
    op.drop_table('plate_aliases')
    op.drop_index(op.f('ix_camera_zones_id'), table_name='camera_zones')
    op.drop_index(op.f('ix_camera_zones_camera_id'), table_name='camera_zones')
    op.drop_table('camera_zones')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_residents_id'), table_name='residents')
    op.drop_index(op.f('ix_residents_flat_number'), table_name='residents')
    op.drop_table('residents')
    op.drop_index(op.f('ix_alert_rules_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_code'), table_name='alert_rules')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
